name: Validate dfx.json

on:
  pull_request:
    branches: 
        - '*'
  push:
    branches: [main]

jobs:
  dfx-json:
    name: Validate dfx.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate dfx.json
        run: python3 -m json.tool dfx.json