name: Frontend

on:
  pull_request:
    branches: 
        - '*'
  push:
    branches: [main]

jobs:
  frontend:
    name: Frontend (TypeScript & Lint)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/polychain_l2_frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: src/polychain_l2_frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/polychain_l2_frontend/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Run frontend tests
        run: npm test