# It sets up the specified version of Node.js, installs dependencies using npm,
# and executes the test suite to ensure code quality and correctness.
# The workflow is triggered for all branches and pull requests targeting any branch.

# performance.yml
name: Performance

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: performance-${{ github.ref }}
  cancel-in-progress: true

jobs:
  measure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.67.1
          override: true

      - name: Cache Cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/target
          key: performance-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run performance script
        run: npm run perf:ci

      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: reports/lighthouse

      - name: Upload performance dashboard
        uses: actions/upload-artifact@v3
        with:
          name: perf-dashboard
          path: reports/dashboard
