name: Rust Backend

on:
  pull_request:
    branches: 
        - '*'
  push:
    branches: [main]

jobs:
  rust-backend:
    name: Rust Backend (Build & Test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build backend
        run: cargo build --workspace --release
      - name: Run backend tests
        run: cargo test --workspace --all-features --all-targets