name: Shell Scripts Quality

on:
  pull_request:
    branches: 
      - '**'
  push:
    branches: [main]

jobs:
  scripts-quality:
    name: Shell Scripts Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: scripts